/*
jCJuegoDestino * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Juegos.Valorant;
import Juegos.Fortnite;
import Juegos.Juegos;
import Juegos.CSGO;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;

/**
 *
 * @author riolu
 */
public class InterfazConvesor extends javax.swing.JFrame {

    /**
     * Creates new form InterfazConvesor
     */
    public InterfazConvesor() {

        initComponents();
        generarJuegosComboBox();
        

    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void generarJuegosComboBox(){
    DefaultComboBoxModel<String> juegoBase = new DefaultComboBoxModel<>();
        juegoBase.addAll(Arrays.asList("Juego Base", "Valorant", "Fortnite", "CSGO"));
        jCJuegoBase.setModel(juegoBase);
        DefaultComboBoxModel<String> juegoDestino = new DefaultComboBoxModel<>();
        juegoDestino.addAll(Arrays.asList("Juego a Convertir", "Valorant", "Fortnite", "CSGO"));
        jCJuegoBase.setModel(juegoBase);
        jCJuegoBase.setSelectedItem("Juego Base");
        jCJuegoDestino.setModel(juegoDestino);
        jCJuegoDestino.setSelectedItem("Juego a Convertir");
}

    
    private void convertirSens(Juegos juegoElegido){
        double sensibilidadBase = Double.parseDouble(txtSensBase.getText());
            if (jCJuegoDestino.getSelectedItem() == "Valorant") {
                juegoElegido.ConvertirSensValorant(sensibilidadBase);

            } else if (jCJuegoDestino.getSelectedItem() == "Fortnite") {
                juegoElegido.ConvertirSensFortnite(sensibilidadBase);

            } else if (jCJuegoDestino.getSelectedItem() == "CSGO") {
                juegoElegido.ConvertirSensCSGO(sensibilidadBase);
            } else{
                txtSensDestino.setText("0");
            }
            String sensibilidadSalida = juegoElegido.getSensSalidaRedondeada();
            txtSensDestino.setText(sensibilidadSalida);
    }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jCJuegoBase = new javax.swing.JComboBox<>();
        jCJuegoDestino = new javax.swing.JComboBox<>();
        txtSensBase = new javax.swing.JTextField();
        txtSensDestino = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jTextField1.setText("Sens:");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 153));

        jLabel1.setFont(new java.awt.Font("Sitka Text", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Conversor de Sensibilidades");

        jCJuegoBase.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jCJuegoBase.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCJuegoBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCJuegoBaseActionPerformed(evt);
            }
        });

        jCJuegoDestino.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jCJuegoDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCJuegoDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCJuegoDestinoActionPerformed(evt);
            }
        });

        txtSensBase.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtSensBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSensBaseActionPerformed(evt);
            }
        });

        txtSensDestino.setEditable(false);
        txtSensDestino.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtSensDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSensDestinoActionPerformed(evt);
            }
        });

        btnCalcular.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnCalcular.setText("CALCULAR");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Sensibilidad");

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Sensibilidad");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCalcular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jCJuegoBase, 0, 150, Short.MAX_VALUE)
                                .addComponent(txtSensBase))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jCJuegoDestino, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtSensDestino))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCJuegoBase, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCJuegoDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSensBase, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSensDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 16, Short.MAX_VALUE)
                .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCJuegoBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCJuegoBaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCJuegoBaseActionPerformed

    private void jCJuegoDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCJuegoDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCJuegoDestinoActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void txtSensBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSensBaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSensBaseActionPerformed

    private void txtSensDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSensDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSensDestinoActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed

        if (jCJuegoBase.getSelectedItem() == "Valorant") {
            Juegos valorant = new Valorant("Valorant");
            convertirSens(valorant);
            
        } else if (jCJuegoBase.getSelectedItem() == "Fortnite"){
             Juegos fortnite = new Fortnite("Fortnite");
          convertirSens(fortnite);
          
        } else if (jCJuegoBase.getSelectedItem() == "CSGO"){
             Juegos csgo = new CSGO("CSGO");
            convertirSens(csgo);
        }
    }//GEN-LAST:event_btnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

 /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazConvesor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JComboBox<String> jCJuegoBase;
    private javax.swing.JComboBox<String> jCJuegoDestino;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtSensBase;
    private javax.swing.JTextField txtSensDestino;
    // End of variables declaration//GEN-END:variables
}
